# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('value', models.CharField(max_length=255, verbose_name='\u503c')),
                ('comment', models.CharField(max_length=255, verbose_name='\u8bf4\u660e')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('operate_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u64cd\u4f5c\u4ebaIP')),
            ],
            options={
                'db_table': 'common_config',
                'verbose_name': '\u901a\u7528\u914d\u7f6e',
                'verbose_name_plural': '\u901a\u7528\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='LoadTestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField(verbose_name='\u6570\u636e\u603b\u91cf')),
                ('hatch_rate', models.IntegerField(blank=True, null=True, verbose_name='\u767b\u9646\u5e76\u53d1')),
                ('data_struct', models.CharField(max_length=255, verbose_name='\u6570\u636e\u6784\u6210')),
                ('scene_struct', models.CharField(max_length=255, verbose_name='\u6d4b\u8bd5\u573a\u666f')),
                ('total_rps', models.FloatField(verbose_name='ToalRps')),
                ('fail_ratio', models.FloatField(blank=True, null=True, verbose_name='\u5931\u8d25\u7387')),
                ('status', models.IntegerField(choices=[(0, '\u672a\u8fd0\u884c'), (1, '\u8fd0\u884c\u4e2d'), (2, '\u5df2\u7ed3\u675f')], verbose_name='\u72b6\u6001')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-start_time'],
                'db_table': 'load_test_record',
                'verbose_name': '\u538b\u6d4b\u8bb0\u5f55\u7ba1\u7406',
                'verbose_name_plural': '\u538b\u6d4b\u8bb0\u5f55\u7ba1\u7406',
            },
        ),
    ]
