// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_demo.proto

package com.vdcoding;

public final class ProtoDemo {
  private ProtoDemo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OnlineUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.vdcoding.OnlineUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 rsp_code = 1;</code>
     */
    int getRspCode();

    /**
     * <code>string product = 2;</code>
     */
    java.lang.String getProduct();
    /**
     * <code>string product = 2;</code>
     */
    com.google.protobuf.ByteString
        getProductBytes();

    /**
     * <code>uint64 query_time = 3;</code>
     */
    long getQueryTime();

    /**
     * <pre>
     *repeated相当于java中的ArrayList，python中的list
     * </pre>
     *
     * <code>repeated uint32 random = 4;</code>
     */
    java.util.List<java.lang.Integer> getRandomList();
    /**
     * <pre>
     *repeated相当于java中的ArrayList，python中的list
     * </pre>
     *
     * <code>repeated uint32 random = 4;</code>
     */
    int getRandomCount();
    /**
     * <pre>
     *repeated相当于java中的ArrayList，python中的list
     * </pre>
     *
     * <code>repeated uint32 random = 4;</code>
     */
    int getRandom(int index);

    /**
     * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
     */
    java.util.List<com.vdcoding.ProtoDemo.OnlineUser.UserInfo> 
        getUserListList();
    /**
     * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
     */
    com.vdcoding.ProtoDemo.OnlineUser.UserInfo getUserList(int index);
    /**
     * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
     */
    int getUserListCount();
    /**
     * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
     */
    java.util.List<? extends com.vdcoding.ProtoDemo.OnlineUser.UserInfoOrBuilder> 
        getUserListOrBuilderList();
    /**
     * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
     */
    com.vdcoding.ProtoDemo.OnlineUser.UserInfoOrBuilder getUserListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.vdcoding.OnlineUser}
   */
  public  static final class OnlineUser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.vdcoding.OnlineUser)
      OnlineUserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OnlineUser.newBuilder() to construct.
    private OnlineUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OnlineUser() {
      rspCode_ = 0;
      product_ = "";
      queryTime_ = 0L;
      random_ = java.util.Collections.emptyList();
      userList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OnlineUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              rspCode_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              product_ = s;
              break;
            }
            case 24: {

              queryTime_ = input.readUInt64();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                random_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              random_.add(input.readUInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                random_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                random_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                userList_ = new java.util.ArrayList<com.vdcoding.ProtoDemo.OnlineUser.UserInfo>();
                mutable_bitField0_ |= 0x00000010;
              }
              userList_.add(
                  input.readMessage(com.vdcoding.ProtoDemo.OnlineUser.UserInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          random_ = java.util.Collections.unmodifiableList(random_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          userList_ = java.util.Collections.unmodifiableList(userList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vdcoding.ProtoDemo.internal_static_com_vdcoding_OnlineUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vdcoding.ProtoDemo.internal_static_com_vdcoding_OnlineUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vdcoding.ProtoDemo.OnlineUser.class, com.vdcoding.ProtoDemo.OnlineUser.Builder.class);
    }

    /**
     * Protobuf enum {@code com.vdcoding.OnlineUser.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.vdcoding.ProtoDemo.OnlineUser.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.vdcoding.OnlineUser.PhoneType)
    }

    public interface UserInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.vdcoding.OnlineUser.UserInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>uint64 uid = 1;</code>
       */
      long getUid();

      /**
       * <code>string usre_name = 2;</code>
       */
      java.lang.String getUsreName();
      /**
       * <code>string usre_name = 2;</code>
       */
      com.google.protobuf.ByteString
          getUsreNameBytes();

      /**
       * <code>.com.vdcoding.OnlineUser.PhoneType type = 3;</code>
       */
      int getTypeValue();
      /**
       * <code>.com.vdcoding.OnlineUser.PhoneType type = 3;</code>
       */
      com.vdcoding.ProtoDemo.OnlineUser.PhoneType getType();

      /**
       * <code>uint32 phone_num = 4;</code>
       */
      int getPhoneNum();

      /**
       * <code>uint32 cli_type = 5;</code>
       */
      int getCliType();
    }
    /**
     * Protobuf type {@code com.vdcoding.OnlineUser.UserInfo}
     */
    public  static final class UserInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.vdcoding.OnlineUser.UserInfo)
        UserInfoOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use UserInfo.newBuilder() to construct.
      private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private UserInfo() {
        uid_ = 0L;
        usreName_ = "";
        type_ = 0;
        phoneNum_ = 0;
        cliType_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private UserInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                uid_ = input.readUInt64();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                usreName_ = s;
                break;
              }
              case 24: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
              case 32: {

                phoneNum_ = input.readUInt32();
                break;
              }
              case 40: {

                cliType_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vdcoding.ProtoDemo.internal_static_com_vdcoding_OnlineUser_UserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vdcoding.ProtoDemo.internal_static_com_vdcoding_OnlineUser_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vdcoding.ProtoDemo.OnlineUser.UserInfo.class, com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder.class);
      }

      public static final int UID_FIELD_NUMBER = 1;
      private long uid_;
      /**
       * <code>uint64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }

      public static final int USRE_NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object usreName_;
      /**
       * <code>string usre_name = 2;</code>
       */
      public java.lang.String getUsreName() {
        java.lang.Object ref = usreName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          usreName_ = s;
          return s;
        }
      }
      /**
       * <code>string usre_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsreNameBytes() {
        java.lang.Object ref = usreName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usreName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 3;
      private int type_;
      /**
       * <code>.com.vdcoding.OnlineUser.PhoneType type = 3;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.vdcoding.OnlineUser.PhoneType type = 3;</code>
       */
      public com.vdcoding.ProtoDemo.OnlineUser.PhoneType getType() {
        com.vdcoding.ProtoDemo.OnlineUser.PhoneType result = com.vdcoding.ProtoDemo.OnlineUser.PhoneType.valueOf(type_);
        return result == null ? com.vdcoding.ProtoDemo.OnlineUser.PhoneType.UNRECOGNIZED : result;
      }

      public static final int PHONE_NUM_FIELD_NUMBER = 4;
      private int phoneNum_;
      /**
       * <code>uint32 phone_num = 4;</code>
       */
      public int getPhoneNum() {
        return phoneNum_;
      }

      public static final int CLI_TYPE_FIELD_NUMBER = 5;
      private int cliType_;
      /**
       * <code>uint32 cli_type = 5;</code>
       */
      public int getCliType() {
        return cliType_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (uid_ != 0L) {
          output.writeUInt64(1, uid_);
        }
        if (!getUsreNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, usreName_);
        }
        if (type_ != com.vdcoding.ProtoDemo.OnlineUser.PhoneType.MOBILE.getNumber()) {
          output.writeEnum(3, type_);
        }
        if (phoneNum_ != 0) {
          output.writeUInt32(4, phoneNum_);
        }
        if (cliType_ != 0) {
          output.writeUInt32(5, cliType_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (uid_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(1, uid_);
        }
        if (!getUsreNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, usreName_);
        }
        if (type_ != com.vdcoding.ProtoDemo.OnlineUser.PhoneType.MOBILE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, type_);
        }
        if (phoneNum_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, phoneNum_);
        }
        if (cliType_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(5, cliType_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.vdcoding.ProtoDemo.OnlineUser.UserInfo)) {
          return super.equals(obj);
        }
        com.vdcoding.ProtoDemo.OnlineUser.UserInfo other = (com.vdcoding.ProtoDemo.OnlineUser.UserInfo) obj;

        boolean result = true;
        result = result && (getUid()
            == other.getUid());
        result = result && getUsreName()
            .equals(other.getUsreName());
        result = result && type_ == other.type_;
        result = result && (getPhoneNum()
            == other.getPhoneNum());
        result = result && (getCliType()
            == other.getCliType());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUid());
        hash = (37 * hash) + USRE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsreName().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (37 * hash) + PHONE_NUM_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneNum();
        hash = (37 * hash) + CLI_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getCliType();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.vdcoding.ProtoDemo.OnlineUser.UserInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.vdcoding.OnlineUser.UserInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.vdcoding.OnlineUser.UserInfo)
          com.vdcoding.ProtoDemo.OnlineUser.UserInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.vdcoding.ProtoDemo.internal_static_com_vdcoding_OnlineUser_UserInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.vdcoding.ProtoDemo.internal_static_com_vdcoding_OnlineUser_UserInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.vdcoding.ProtoDemo.OnlineUser.UserInfo.class, com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder.class);
        }

        // Construct using com.vdcoding.ProtoDemo.OnlineUser.UserInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          uid_ = 0L;

          usreName_ = "";

          type_ = 0;

          phoneNum_ = 0;

          cliType_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.vdcoding.ProtoDemo.internal_static_com_vdcoding_OnlineUser_UserInfo_descriptor;
        }

        public com.vdcoding.ProtoDemo.OnlineUser.UserInfo getDefaultInstanceForType() {
          return com.vdcoding.ProtoDemo.OnlineUser.UserInfo.getDefaultInstance();
        }

        public com.vdcoding.ProtoDemo.OnlineUser.UserInfo build() {
          com.vdcoding.ProtoDemo.OnlineUser.UserInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.vdcoding.ProtoDemo.OnlineUser.UserInfo buildPartial() {
          com.vdcoding.ProtoDemo.OnlineUser.UserInfo result = new com.vdcoding.ProtoDemo.OnlineUser.UserInfo(this);
          result.uid_ = uid_;
          result.usreName_ = usreName_;
          result.type_ = type_;
          result.phoneNum_ = phoneNum_;
          result.cliType_ = cliType_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.vdcoding.ProtoDemo.OnlineUser.UserInfo) {
            return mergeFrom((com.vdcoding.ProtoDemo.OnlineUser.UserInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.vdcoding.ProtoDemo.OnlineUser.UserInfo other) {
          if (other == com.vdcoding.ProtoDemo.OnlineUser.UserInfo.getDefaultInstance()) return this;
          if (other.getUid() != 0L) {
            setUid(other.getUid());
          }
          if (!other.getUsreName().isEmpty()) {
            usreName_ = other.usreName_;
            onChanged();
          }
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          if (other.getPhoneNum() != 0) {
            setPhoneNum(other.getPhoneNum());
          }
          if (other.getCliType() != 0) {
            setCliType(other.getCliType());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.vdcoding.ProtoDemo.OnlineUser.UserInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.vdcoding.ProtoDemo.OnlineUser.UserInfo) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long uid_ ;
        /**
         * <code>uint64 uid = 1;</code>
         */
        public long getUid() {
          return uid_;
        }
        /**
         * <code>uint64 uid = 1;</code>
         */
        public Builder setUid(long value) {
          
          uid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint64 uid = 1;</code>
         */
        public Builder clearUid() {
          
          uid_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object usreName_ = "";
        /**
         * <code>string usre_name = 2;</code>
         */
        public java.lang.String getUsreName() {
          java.lang.Object ref = usreName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            usreName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string usre_name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getUsreNameBytes() {
          java.lang.Object ref = usreName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            usreName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string usre_name = 2;</code>
         */
        public Builder setUsreName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          usreName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string usre_name = 2;</code>
         */
        public Builder clearUsreName() {
          
          usreName_ = getDefaultInstance().getUsreName();
          onChanged();
          return this;
        }
        /**
         * <code>string usre_name = 2;</code>
         */
        public Builder setUsreNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          usreName_ = value;
          onChanged();
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.com.vdcoding.OnlineUser.PhoneType type = 3;</code>
         */
        public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.com.vdcoding.OnlineUser.PhoneType type = 3;</code>
         */
        public Builder setTypeValue(int value) {
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.com.vdcoding.OnlineUser.PhoneType type = 3;</code>
         */
        public com.vdcoding.ProtoDemo.OnlineUser.PhoneType getType() {
          com.vdcoding.ProtoDemo.OnlineUser.PhoneType result = com.vdcoding.ProtoDemo.OnlineUser.PhoneType.valueOf(type_);
          return result == null ? com.vdcoding.ProtoDemo.OnlineUser.PhoneType.UNRECOGNIZED : result;
        }
        /**
         * <code>.com.vdcoding.OnlineUser.PhoneType type = 3;</code>
         */
        public Builder setType(com.vdcoding.ProtoDemo.OnlineUser.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.com.vdcoding.OnlineUser.PhoneType type = 3;</code>
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }

        private int phoneNum_ ;
        /**
         * <code>uint32 phone_num = 4;</code>
         */
        public int getPhoneNum() {
          return phoneNum_;
        }
        /**
         * <code>uint32 phone_num = 4;</code>
         */
        public Builder setPhoneNum(int value) {
          
          phoneNum_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 phone_num = 4;</code>
         */
        public Builder clearPhoneNum() {
          
          phoneNum_ = 0;
          onChanged();
          return this;
        }

        private int cliType_ ;
        /**
         * <code>uint32 cli_type = 5;</code>
         */
        public int getCliType() {
          return cliType_;
        }
        /**
         * <code>uint32 cli_type = 5;</code>
         */
        public Builder setCliType(int value) {
          
          cliType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 cli_type = 5;</code>
         */
        public Builder clearCliType() {
          
          cliType_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.vdcoding.OnlineUser.UserInfo)
      }

      // @@protoc_insertion_point(class_scope:com.vdcoding.OnlineUser.UserInfo)
      private static final com.vdcoding.ProtoDemo.OnlineUser.UserInfo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.vdcoding.ProtoDemo.OnlineUser.UserInfo();
      }

      public static com.vdcoding.ProtoDemo.OnlineUser.UserInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<UserInfo>
          PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
        public UserInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserInfo(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<UserInfo> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<UserInfo> getParserForType() {
        return PARSER;
      }

      public com.vdcoding.ProtoDemo.OnlineUser.UserInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int RSP_CODE_FIELD_NUMBER = 1;
    private int rspCode_;
    /**
     * <code>uint32 rsp_code = 1;</code>
     */
    public int getRspCode() {
      return rspCode_;
    }

    public static final int PRODUCT_FIELD_NUMBER = 2;
    private volatile java.lang.Object product_;
    /**
     * <code>string product = 2;</code>
     */
    public java.lang.String getProduct() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        product_ = s;
        return s;
      }
    }
    /**
     * <code>string product = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        product_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUERY_TIME_FIELD_NUMBER = 3;
    private long queryTime_;
    /**
     * <code>uint64 query_time = 3;</code>
     */
    public long getQueryTime() {
      return queryTime_;
    }

    public static final int RANDOM_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> random_;
    /**
     * <pre>
     *repeated相当于java中的ArrayList，python中的list
     * </pre>
     *
     * <code>repeated uint32 random = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getRandomList() {
      return random_;
    }
    /**
     * <pre>
     *repeated相当于java中的ArrayList，python中的list
     * </pre>
     *
     * <code>repeated uint32 random = 4;</code>
     */
    public int getRandomCount() {
      return random_.size();
    }
    /**
     * <pre>
     *repeated相当于java中的ArrayList，python中的list
     * </pre>
     *
     * <code>repeated uint32 random = 4;</code>
     */
    public int getRandom(int index) {
      return random_.get(index);
    }
    private int randomMemoizedSerializedSize = -1;

    public static final int USER_LIST_FIELD_NUMBER = 5;
    private java.util.List<com.vdcoding.ProtoDemo.OnlineUser.UserInfo> userList_;
    /**
     * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
     */
    public java.util.List<com.vdcoding.ProtoDemo.OnlineUser.UserInfo> getUserListList() {
      return userList_;
    }
    /**
     * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
     */
    public java.util.List<? extends com.vdcoding.ProtoDemo.OnlineUser.UserInfoOrBuilder> 
        getUserListOrBuilderList() {
      return userList_;
    }
    /**
     * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
     */
    public int getUserListCount() {
      return userList_.size();
    }
    /**
     * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
     */
    public com.vdcoding.ProtoDemo.OnlineUser.UserInfo getUserList(int index) {
      return userList_.get(index);
    }
    /**
     * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
     */
    public com.vdcoding.ProtoDemo.OnlineUser.UserInfoOrBuilder getUserListOrBuilder(
        int index) {
      return userList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (rspCode_ != 0) {
        output.writeUInt32(1, rspCode_);
      }
      if (!getProductBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, product_);
      }
      if (queryTime_ != 0L) {
        output.writeUInt64(3, queryTime_);
      }
      if (getRandomList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(randomMemoizedSerializedSize);
      }
      for (int i = 0; i < random_.size(); i++) {
        output.writeUInt32NoTag(random_.get(i));
      }
      for (int i = 0; i < userList_.size(); i++) {
        output.writeMessage(5, userList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rspCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, rspCode_);
      }
      if (!getProductBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, product_);
      }
      if (queryTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, queryTime_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < random_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(random_.get(i));
        }
        size += dataSize;
        if (!getRandomList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        randomMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < userList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, userList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vdcoding.ProtoDemo.OnlineUser)) {
        return super.equals(obj);
      }
      com.vdcoding.ProtoDemo.OnlineUser other = (com.vdcoding.ProtoDemo.OnlineUser) obj;

      boolean result = true;
      result = result && (getRspCode()
          == other.getRspCode());
      result = result && getProduct()
          .equals(other.getProduct());
      result = result && (getQueryTime()
          == other.getQueryTime());
      result = result && getRandomList()
          .equals(other.getRandomList());
      result = result && getUserListList()
          .equals(other.getUserListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RSP_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getRspCode();
      hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getProduct().hashCode();
      hash = (37 * hash) + QUERY_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getQueryTime());
      if (getRandomCount() > 0) {
        hash = (37 * hash) + RANDOM_FIELD_NUMBER;
        hash = (53 * hash) + getRandomList().hashCode();
      }
      if (getUserListCount() > 0) {
        hash = (37 * hash) + USER_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getUserListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vdcoding.ProtoDemo.OnlineUser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vdcoding.ProtoDemo.OnlineUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vdcoding.ProtoDemo.OnlineUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.vdcoding.OnlineUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.vdcoding.OnlineUser)
        com.vdcoding.ProtoDemo.OnlineUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vdcoding.ProtoDemo.internal_static_com_vdcoding_OnlineUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vdcoding.ProtoDemo.internal_static_com_vdcoding_OnlineUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vdcoding.ProtoDemo.OnlineUser.class, com.vdcoding.ProtoDemo.OnlineUser.Builder.class);
      }

      // Construct using com.vdcoding.ProtoDemo.OnlineUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        rspCode_ = 0;

        product_ = "";

        queryTime_ = 0L;

        random_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        if (userListBuilder_ == null) {
          userList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          userListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vdcoding.ProtoDemo.internal_static_com_vdcoding_OnlineUser_descriptor;
      }

      public com.vdcoding.ProtoDemo.OnlineUser getDefaultInstanceForType() {
        return com.vdcoding.ProtoDemo.OnlineUser.getDefaultInstance();
      }

      public com.vdcoding.ProtoDemo.OnlineUser build() {
        com.vdcoding.ProtoDemo.OnlineUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.vdcoding.ProtoDemo.OnlineUser buildPartial() {
        com.vdcoding.ProtoDemo.OnlineUser result = new com.vdcoding.ProtoDemo.OnlineUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.rspCode_ = rspCode_;
        result.product_ = product_;
        result.queryTime_ = queryTime_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          random_ = java.util.Collections.unmodifiableList(random_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.random_ = random_;
        if (userListBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            userList_ = java.util.Collections.unmodifiableList(userList_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.userList_ = userList_;
        } else {
          result.userList_ = userListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vdcoding.ProtoDemo.OnlineUser) {
          return mergeFrom((com.vdcoding.ProtoDemo.OnlineUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vdcoding.ProtoDemo.OnlineUser other) {
        if (other == com.vdcoding.ProtoDemo.OnlineUser.getDefaultInstance()) return this;
        if (other.getRspCode() != 0) {
          setRspCode(other.getRspCode());
        }
        if (!other.getProduct().isEmpty()) {
          product_ = other.product_;
          onChanged();
        }
        if (other.getQueryTime() != 0L) {
          setQueryTime(other.getQueryTime());
        }
        if (!other.random_.isEmpty()) {
          if (random_.isEmpty()) {
            random_ = other.random_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureRandomIsMutable();
            random_.addAll(other.random_);
          }
          onChanged();
        }
        if (userListBuilder_ == null) {
          if (!other.userList_.isEmpty()) {
            if (userList_.isEmpty()) {
              userList_ = other.userList_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureUserListIsMutable();
              userList_.addAll(other.userList_);
            }
            onChanged();
          }
        } else {
          if (!other.userList_.isEmpty()) {
            if (userListBuilder_.isEmpty()) {
              userListBuilder_.dispose();
              userListBuilder_ = null;
              userList_ = other.userList_;
              bitField0_ = (bitField0_ & ~0x00000010);
              userListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserListFieldBuilder() : null;
            } else {
              userListBuilder_.addAllMessages(other.userList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vdcoding.ProtoDemo.OnlineUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vdcoding.ProtoDemo.OnlineUser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rspCode_ ;
      /**
       * <code>uint32 rsp_code = 1;</code>
       */
      public int getRspCode() {
        return rspCode_;
      }
      /**
       * <code>uint32 rsp_code = 1;</code>
       */
      public Builder setRspCode(int value) {
        
        rspCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 rsp_code = 1;</code>
       */
      public Builder clearRspCode() {
        
        rspCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object product_ = "";
      /**
       * <code>string product = 2;</code>
       */
      public java.lang.String getProduct() {
        java.lang.Object ref = product_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          product_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string product = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProductBytes() {
        java.lang.Object ref = product_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          product_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string product = 2;</code>
       */
      public Builder setProduct(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        product_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string product = 2;</code>
       */
      public Builder clearProduct() {
        
        product_ = getDefaultInstance().getProduct();
        onChanged();
        return this;
      }
      /**
       * <code>string product = 2;</code>
       */
      public Builder setProductBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        product_ = value;
        onChanged();
        return this;
      }

      private long queryTime_ ;
      /**
       * <code>uint64 query_time = 3;</code>
       */
      public long getQueryTime() {
        return queryTime_;
      }
      /**
       * <code>uint64 query_time = 3;</code>
       */
      public Builder setQueryTime(long value) {
        
        queryTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 query_time = 3;</code>
       */
      public Builder clearQueryTime() {
        
        queryTime_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> random_ = java.util.Collections.emptyList();
      private void ensureRandomIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          random_ = new java.util.ArrayList<java.lang.Integer>(random_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       *repeated相当于java中的ArrayList，python中的list
       * </pre>
       *
       * <code>repeated uint32 random = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getRandomList() {
        return java.util.Collections.unmodifiableList(random_);
      }
      /**
       * <pre>
       *repeated相当于java中的ArrayList，python中的list
       * </pre>
       *
       * <code>repeated uint32 random = 4;</code>
       */
      public int getRandomCount() {
        return random_.size();
      }
      /**
       * <pre>
       *repeated相当于java中的ArrayList，python中的list
       * </pre>
       *
       * <code>repeated uint32 random = 4;</code>
       */
      public int getRandom(int index) {
        return random_.get(index);
      }
      /**
       * <pre>
       *repeated相当于java中的ArrayList，python中的list
       * </pre>
       *
       * <code>repeated uint32 random = 4;</code>
       */
      public Builder setRandom(
          int index, int value) {
        ensureRandomIsMutable();
        random_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *repeated相当于java中的ArrayList，python中的list
       * </pre>
       *
       * <code>repeated uint32 random = 4;</code>
       */
      public Builder addRandom(int value) {
        ensureRandomIsMutable();
        random_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *repeated相当于java中的ArrayList，python中的list
       * </pre>
       *
       * <code>repeated uint32 random = 4;</code>
       */
      public Builder addAllRandom(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureRandomIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, random_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *repeated相当于java中的ArrayList，python中的list
       * </pre>
       *
       * <code>repeated uint32 random = 4;</code>
       */
      public Builder clearRandom() {
        random_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private java.util.List<com.vdcoding.ProtoDemo.OnlineUser.UserInfo> userList_ =
        java.util.Collections.emptyList();
      private void ensureUserListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          userList_ = new java.util.ArrayList<com.vdcoding.ProtoDemo.OnlineUser.UserInfo>(userList_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.vdcoding.ProtoDemo.OnlineUser.UserInfo, com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder, com.vdcoding.ProtoDemo.OnlineUser.UserInfoOrBuilder> userListBuilder_;

      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public java.util.List<com.vdcoding.ProtoDemo.OnlineUser.UserInfo> getUserListList() {
        if (userListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userList_);
        } else {
          return userListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public int getUserListCount() {
        if (userListBuilder_ == null) {
          return userList_.size();
        } else {
          return userListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public com.vdcoding.ProtoDemo.OnlineUser.UserInfo getUserList(int index) {
        if (userListBuilder_ == null) {
          return userList_.get(index);
        } else {
          return userListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public Builder setUserList(
          int index, com.vdcoding.ProtoDemo.OnlineUser.UserInfo value) {
        if (userListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserListIsMutable();
          userList_.set(index, value);
          onChanged();
        } else {
          userListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public Builder setUserList(
          int index, com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder builderForValue) {
        if (userListBuilder_ == null) {
          ensureUserListIsMutable();
          userList_.set(index, builderForValue.build());
          onChanged();
        } else {
          userListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public Builder addUserList(com.vdcoding.ProtoDemo.OnlineUser.UserInfo value) {
        if (userListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserListIsMutable();
          userList_.add(value);
          onChanged();
        } else {
          userListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public Builder addUserList(
          int index, com.vdcoding.ProtoDemo.OnlineUser.UserInfo value) {
        if (userListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserListIsMutable();
          userList_.add(index, value);
          onChanged();
        } else {
          userListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public Builder addUserList(
          com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder builderForValue) {
        if (userListBuilder_ == null) {
          ensureUserListIsMutable();
          userList_.add(builderForValue.build());
          onChanged();
        } else {
          userListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public Builder addUserList(
          int index, com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder builderForValue) {
        if (userListBuilder_ == null) {
          ensureUserListIsMutable();
          userList_.add(index, builderForValue.build());
          onChanged();
        } else {
          userListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public Builder addAllUserList(
          java.lang.Iterable<? extends com.vdcoding.ProtoDemo.OnlineUser.UserInfo> values) {
        if (userListBuilder_ == null) {
          ensureUserListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userList_);
          onChanged();
        } else {
          userListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public Builder clearUserList() {
        if (userListBuilder_ == null) {
          userList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          userListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public Builder removeUserList(int index) {
        if (userListBuilder_ == null) {
          ensureUserListIsMutable();
          userList_.remove(index);
          onChanged();
        } else {
          userListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder getUserListBuilder(
          int index) {
        return getUserListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public com.vdcoding.ProtoDemo.OnlineUser.UserInfoOrBuilder getUserListOrBuilder(
          int index) {
        if (userListBuilder_ == null) {
          return userList_.get(index);  } else {
          return userListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public java.util.List<? extends com.vdcoding.ProtoDemo.OnlineUser.UserInfoOrBuilder> 
           getUserListOrBuilderList() {
        if (userListBuilder_ != null) {
          return userListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userList_);
        }
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder addUserListBuilder() {
        return getUserListFieldBuilder().addBuilder(
            com.vdcoding.ProtoDemo.OnlineUser.UserInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder addUserListBuilder(
          int index) {
        return getUserListFieldBuilder().addBuilder(
            index, com.vdcoding.ProtoDemo.OnlineUser.UserInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.vdcoding.OnlineUser.UserInfo user_list = 5;</code>
       */
      public java.util.List<com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder> 
           getUserListBuilderList() {
        return getUserListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.vdcoding.ProtoDemo.OnlineUser.UserInfo, com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder, com.vdcoding.ProtoDemo.OnlineUser.UserInfoOrBuilder> 
          getUserListFieldBuilder() {
        if (userListBuilder_ == null) {
          userListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.vdcoding.ProtoDemo.OnlineUser.UserInfo, com.vdcoding.ProtoDemo.OnlineUser.UserInfo.Builder, com.vdcoding.ProtoDemo.OnlineUser.UserInfoOrBuilder>(
                  userList_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          userList_ = null;
        }
        return userListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.vdcoding.OnlineUser)
    }

    // @@protoc_insertion_point(class_scope:com.vdcoding.OnlineUser)
    private static final com.vdcoding.ProtoDemo.OnlineUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vdcoding.ProtoDemo.OnlineUser();
    }

    public static com.vdcoding.ProtoDemo.OnlineUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OnlineUser>
        PARSER = new com.google.protobuf.AbstractParser<OnlineUser>() {
      public OnlineUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OnlineUser(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OnlineUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OnlineUser> getParserForType() {
      return PARSER;
    }

    public com.vdcoding.ProtoDemo.OnlineUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vdcoding_OnlineUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vdcoding_OnlineUser_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vdcoding_OnlineUser_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vdcoding_OnlineUser_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protobuf_demo.proto\022\014com.vdcoding\"\272\002\n\n" +
      "OnlineUser\022\020\n\010rsp_code\030\001 \001(\r\022\017\n\007product\030" +
      "\002 \001(\t\022\022\n\nquery_time\030\003 \001(\004\022\016\n\006random\030\004 \003(" +
      "\r\0224\n\tuser_list\030\005 \003(\0132!.com.vdcoding.Onli" +
      "neUser.UserInfo\032\201\001\n\010UserInfo\022\013\n\003uid\030\001 \001(" +
      "\004\022\021\n\tusre_name\030\002 \001(\t\0220\n\004type\030\003 \001(\0162\".com" +
      ".vdcoding.OnlineUser.PhoneType\022\021\n\tphone_" +
      "num\030\004 \001(\r\022\020\n\010cli_type\030\005 \001(\r\"+\n\tPhoneType" +
      "\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002B\033\n\014com." +
      "vdcodingB\tProtoDemoH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_vdcoding_OnlineUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vdcoding_OnlineUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vdcoding_OnlineUser_descriptor,
        new java.lang.String[] { "RspCode", "Product", "QueryTime", "Random", "UserList", });
    internal_static_com_vdcoding_OnlineUser_UserInfo_descriptor =
      internal_static_com_vdcoding_OnlineUser_descriptor.getNestedTypes().get(0);
    internal_static_com_vdcoding_OnlineUser_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vdcoding_OnlineUser_UserInfo_descriptor,
        new java.lang.String[] { "Uid", "UsreName", "Type", "PhoneNum", "CliType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
